BOOTSTRAP_VERSION=5.3.8

bootstrap:
	curl -s -o css/bootstrap-$(BOOTSTRAP_VERSION).min.css https://cdn.jsdelivr.net/npm/bootstrap@$(BOOTSTRAP_VERSION)/dist/css/bootstrap.min.css
	curl -s -o javascript/bootstrap-$(BOOTSTRAP_VERSION).bundle.min.js https://cdn.jsdelivr.net/npm/bootstrap@$(BOOTSTRAP_VERSION)/dist/js/bootstrap.bundle.min.js
