// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: grpc/org_sfomuseum_embeddingsdb_service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EmbeddingsDBService_AddRecord_FullMethodName        = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/AddRecord"
	EmbeddingsDBService_GetRecord_FullMethodName        = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/GetRecord"
	EmbeddingsDBService_QueryRecords_FullMethodName     = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/QueryRecords"
	EmbeddingsDBService_QueryRecordsById_FullMethodName = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/QueryRecordsById"
)

// EmbeddingsDBServiceClient is the client API for EmbeddingsDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbeddingsDBServiceClient interface {
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	QueryRecords(ctx context.Context, in *QueryRecordsRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error)
	QueryRecordsById(ctx context.Context, in *QueryRecordsByIdRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error)
}

type embeddingsDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingsDBServiceClient(cc grpc.ClientConnInterface) EmbeddingsDBServiceClient {
	return &embeddingsDBServiceClient{cc}
}

func (c *embeddingsDBServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_AddRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_GetRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) QueryRecords(ctx context.Context, in *QueryRecordsRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error) {
	out := new(QueryRecordsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_QueryRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) QueryRecordsById(ctx context.Context, in *QueryRecordsByIdRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error) {
	out := new(QueryRecordsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_QueryRecordsById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingsDBServiceServer is the server API for EmbeddingsDBService service.
// All implementations must embed UnimplementedEmbeddingsDBServiceServer
// for forward compatibility
type EmbeddingsDBServiceServer interface {
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	QueryRecords(context.Context, *QueryRecordsRequest) (*QueryRecordsResponse, error)
	QueryRecordsById(context.Context, *QueryRecordsByIdRequest) (*QueryRecordsResponse, error)
	mustEmbedUnimplementedEmbeddingsDBServiceServer()
}

// UnimplementedEmbeddingsDBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmbeddingsDBServiceServer struct {
}

func (UnimplementedEmbeddingsDBServiceServer) AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) QueryRecords(context.Context, *QueryRecordsRequest) (*QueryRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRecords not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) QueryRecordsById(context.Context, *QueryRecordsByIdRequest) (*QueryRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRecordsById not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) mustEmbedUnimplementedEmbeddingsDBServiceServer() {}

// UnsafeEmbeddingsDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingsDBServiceServer will
// result in compilation errors.
type UnsafeEmbeddingsDBServiceServer interface {
	mustEmbedUnimplementedEmbeddingsDBServiceServer()
}

func RegisterEmbeddingsDBServiceServer(s grpc.ServiceRegistrar, srv EmbeddingsDBServiceServer) {
	s.RegisterService(&EmbeddingsDBService_ServiceDesc, srv)
}

func _EmbeddingsDBService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_AddRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_QueryRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).QueryRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_QueryRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).QueryRecords(ctx, req.(*QueryRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_QueryRecordsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecordsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).QueryRecordsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_QueryRecordsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).QueryRecordsById(ctx, req.(*QueryRecordsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingsDBService_ServiceDesc is the grpc.ServiceDesc for EmbeddingsDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingsDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org_sfomuseum_embeddingsdb_service.EmbeddingsDBService",
	HandlerType: (*EmbeddingsDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _EmbeddingsDBService_AddRecord_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _EmbeddingsDBService_GetRecord_Handler,
		},
		{
			MethodName: "QueryRecords",
			Handler:    _EmbeddingsDBService_QueryRecords_Handler,
		},
		{
			MethodName: "QueryRecordsById",
			Handler:    _EmbeddingsDBService_QueryRecordsById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/org_sfomuseum_embeddingsdb_service.proto",
}
