// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: grpc/org_sfomuseum_embeddingsdb_service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EmbeddingsDBService_AddRecord_FullMethodName          = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/AddRecord"
	EmbeddingsDBService_GetRecord_FullMethodName          = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/GetRecord"
	EmbeddingsDBService_SimilarRecords_FullMethodName     = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/SimilarRecords"
	EmbeddingsDBService_SimilarRecordsById_FullMethodName = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/SimilarRecordsById"
	EmbeddingsDBService_GetModels_FullMethodName          = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/GetModels"
	EmbeddingsDBService_GetProviders_FullMethodName       = "/org_sfomuseum_embeddingsdb_service.EmbeddingsDBService/GetProviders"
)

// EmbeddingsDBServiceClient is the client API for EmbeddingsDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbeddingsDBServiceClient interface {
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	SimilarRecords(ctx context.Context, in *SimilarRecordsRequest, opts ...grpc.CallOption) (*SimilarRecordsResponse, error)
	SimilarRecordsById(ctx context.Context, in *SimilarRecordsByIdRequest, opts ...grpc.CallOption) (*SimilarRecordsResponse, error)
	GetModels(ctx context.Context, in *GetModelsRequest, opts ...grpc.CallOption) (*GetModelsResponse, error)
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error)
}

type embeddingsDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingsDBServiceClient(cc grpc.ClientConnInterface) EmbeddingsDBServiceClient {
	return &embeddingsDBServiceClient{cc}
}

func (c *embeddingsDBServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_AddRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_GetRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) SimilarRecords(ctx context.Context, in *SimilarRecordsRequest, opts ...grpc.CallOption) (*SimilarRecordsResponse, error) {
	out := new(SimilarRecordsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_SimilarRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) SimilarRecordsById(ctx context.Context, in *SimilarRecordsByIdRequest, opts ...grpc.CallOption) (*SimilarRecordsResponse, error) {
	out := new(SimilarRecordsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_SimilarRecordsById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) GetModels(ctx context.Context, in *GetModelsRequest, opts ...grpc.CallOption) (*GetModelsResponse, error) {
	out := new(GetModelsResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_GetModels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingsDBServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error) {
	out := new(GetProvidersResponse)
	err := c.cc.Invoke(ctx, EmbeddingsDBService_GetProviders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingsDBServiceServer is the server API for EmbeddingsDBService service.
// All implementations must embed UnimplementedEmbeddingsDBServiceServer
// for forward compatibility
type EmbeddingsDBServiceServer interface {
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	SimilarRecords(context.Context, *SimilarRecordsRequest) (*SimilarRecordsResponse, error)
	SimilarRecordsById(context.Context, *SimilarRecordsByIdRequest) (*SimilarRecordsResponse, error)
	GetModels(context.Context, *GetModelsRequest) (*GetModelsResponse, error)
	GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error)
	mustEmbedUnimplementedEmbeddingsDBServiceServer()
}

// UnimplementedEmbeddingsDBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmbeddingsDBServiceServer struct {
}

func (UnimplementedEmbeddingsDBServiceServer) AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) SimilarRecords(context.Context, *SimilarRecordsRequest) (*SimilarRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimilarRecords not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) SimilarRecordsById(context.Context, *SimilarRecordsByIdRequest) (*SimilarRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimilarRecordsById not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) GetModels(context.Context, *GetModelsRequest) (*GetModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModels not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedEmbeddingsDBServiceServer) mustEmbedUnimplementedEmbeddingsDBServiceServer() {}

// UnsafeEmbeddingsDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingsDBServiceServer will
// result in compilation errors.
type UnsafeEmbeddingsDBServiceServer interface {
	mustEmbedUnimplementedEmbeddingsDBServiceServer()
}

func RegisterEmbeddingsDBServiceServer(s grpc.ServiceRegistrar, srv EmbeddingsDBServiceServer) {
	s.RegisterService(&EmbeddingsDBService_ServiceDesc, srv)
}

func _EmbeddingsDBService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_AddRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_SimilarRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).SimilarRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_SimilarRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).SimilarRecords(ctx, req.(*SimilarRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_SimilarRecordsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarRecordsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).SimilarRecordsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_SimilarRecordsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).SimilarRecordsById(ctx, req.(*SimilarRecordsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_GetModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).GetModels(ctx, req.(*GetModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingsDBService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsDBServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingsDBService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsDBServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingsDBService_ServiceDesc is the grpc.ServiceDesc for EmbeddingsDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingsDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org_sfomuseum_embeddingsdb_service.EmbeddingsDBService",
	HandlerType: (*EmbeddingsDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _EmbeddingsDBService_AddRecord_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _EmbeddingsDBService_GetRecord_Handler,
		},
		{
			MethodName: "SimilarRecords",
			Handler:    _EmbeddingsDBService_SimilarRecords_Handler,
		},
		{
			MethodName: "SimilarRecordsById",
			Handler:    _EmbeddingsDBService_SimilarRecordsById_Handler,
		},
		{
			MethodName: "GetModels",
			Handler:    _EmbeddingsDBService_GetModels_Handler,
		},
		{
			MethodName: "GetProviders",
			Handler:    _EmbeddingsDBService_GetProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/org_sfomuseum_embeddingsdb_service.proto",
}
